# Generated by Django 2.1.1 on 2020-01-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_img',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='封面图片'),
        ),
    ]
